import type { Address } from 'viem';
import { requireStore,K } from './store';
import type { ProtocolSnapshot,TokenSnapshot } from '@/lib/read-model';

export async function getProtocol(){return requireStore().get<ProtocolSnapshot>(K.protocol);}
export async function getAllTokens(){return(await requireStore().hgetall<Record<string,TokenSnapshot>>(K.tokens))||{};}
async function protocolAfterTokenRead(maxTokenBlock:number,initial:ProtocolSnapshot){if(maxTokenBlock<=initial.blockNumber)return initial;const newer=await getProtocol();if(!newer||newer.blockNumber<maxTokenBlock)throw new Error('READ_MODEL_COMMIT_IN_PROGRESS');return newer;}
export async function getConsistentAllTokens(){const first=await getProtocol();if(!first)return null;const tokens=await getAllTokens();const maxUpdated=Object.values(tokens).reduce((m,t)=>Math.max(m,Number(t?.updatedBlock||0)),0);const protocol=await protocolAfterTokenRead(maxUpdated,first);return{protocol,tokens};}
export async function getWalletTokens(address:Address){const r=requireStore();const ids=(await r.smembers(K.wallet(address)))as string[];if(!ids.length)return[];const pipe=r.pipeline();ids.forEach(id=>pipe.hget(K.tokens,id));const rows=await pipe.exec<TokenSnapshot[]>();return rows.filter((t):t is TokenSnapshot=>Boolean(t&&t.owner&&!t.burned&&t.owner.toLowerCase()===address.toLowerCase())).sort((a,b)=>a.id-b.id);}
export async function getConsistentWallet(address:Address){const first=await getProtocol();if(!first)return null;const tokens=await getWalletTokens(address);const maxUpdated=tokens.reduce((m,t)=>Math.max(m,Number(t.updatedBlock||0)),0);const protocol=await protocolAfterTokenRead(maxUpdated,first);return{protocol,tokens};}
export async function getConsistentToken(id:number){const r=requireStore();const first=await getProtocol();if(!first)return null;const supply=Number(BigInt(first.startingPopulation||'0')||BigInt(first.totalMinted||'0'));if(id>supply)return{protocol:first,token:null,outOfRange:true};const token=await r.hget<TokenSnapshot>(K.tokens,String(id));if(!token)return{protocol:first,token:null,outOfRange:false};const protocol=await protocolAfterTokenRead(Number(token.updatedBlock||0),first);return{protocol,token,outOfRange:false};}
export async function compactStadium(){const r=requireStore();let protocol=await getProtocol();if(!protocol)return null;const stadium=await r.get<{blockNumber:number;rows:number[][]}>(K.stadium);if(!stadium)throw new Error('STADIUM_BOOTSTRAPPING');if(stadium.blockNumber>protocol.blockNumber){const newer=await getProtocol();if(!newer||newer.blockNumber<stadium.blockNumber)throw new Error('READ_MODEL_COMMIT_IN_PROGRESS');protocol=newer;}return{protocol,rows:stadium.rows,indexedAt:protocol.indexedAt,stadiumBlock:stadium.blockNumber};}
export async function compactEndgame(){const r=requireStore();let protocol=await getProtocol();if(!protocol)return null;const table=await r.get<{blockNumber:number;active:boolean;live:Array<TokenSnapshot&{status:string;voteValid:boolean}>;voted:number}>(K.endgame);if(!table)throw new Error('ENDGAME_BOOTSTRAPPING');if(table.blockNumber>protocol.blockNumber){const newer=await getProtocol();if(!newer||newer.blockNumber<table.blockNumber)throw new Error('READ_MODEL_COMMIT_IN_PROGRESS');protocol=newer;}return{protocol,live:table.live||[],voted:Number(table.voted||0),indexedAt:protocol.indexedAt,tableBlock:table.blockNumber};}
