FROM node:22-alpine AS runner
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts
COPY tsconfig.json ./
COPY src ./src
COPY worker ./worker
CMD ["npm","run","indexer"]
