'use client';
import { useMemo, useState } from 'react';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useAccount, useReadContract, useReadContracts } from 'wagmi';
import { isAddress, zeroAddress, zeroHash } from 'viem';
import { CONTRACTS, COMMUNITY_CONTROLLER_ABI, GAME_ENGINE_ABI, MAX_SUPPLY, ZERO_ADDRESS } from '@/lib/constants';
import { Panel, Kicker } from '@/components/Terminal';
import { TxButton } from '@/components/TxButton';

type CommunityRow = { id: number; collection: string; walletRoot: string; allocation: number; minted: number; mode: number; active: boolean };
const modeName = (m: number) => m === 0 ? 'NFT HOLDERS' : m === 1 ? 'WALLET LIST' : 'BOTH';
const short = (s: string) => s && s !== zeroAddress ? `${s.slice(0, 6)}…${s.slice(-4)}` : '—';

export default function Communities() {
  const { address } = useAccount(); const [open, setOpen] = useState(false); const [form, setForm] = useState({ allocation: '50', mode: 2, collection: '', root: zeroHash });
  const countR = useReadContract({ address: CONTRACTS.communityController, abi: COMMUNITY_CONTROLLER_ABI, functionName: 'communityCount', query: { enabled: CONTRACTS.communityController !== ZERO_ADDRESS, refetchInterval: 5000 } }); const count = Number(countR.data || 0n);
  const rowsR = useReadContracts({ contracts: Array.from({ length: count }, (_, id) => ({ address: CONTRACTS.communityController, abi: COMMUNITY_CONTROLLER_ABI, functionName: 'communities', args: [BigInt(id)] })) as any, allowFailure: true, query: { enabled: count > 0, refetchInterval: 5000 } });
  const reservedR = useReadContract({ address: CONTRACTS.communityController, abi: COMMUNITY_CONTROLLER_ABI, functionName: 'totalReservedRemaining', query: { enabled: CONTRACTS.communityController !== ZERO_ADDRESS, refetchInterval: 5000 } });
  const mintedR = useReadContract({ address: CONTRACTS.gameEngine, abi: GAME_ENGINE_ABI, functionName: 's_totalMinted', query: { enabled: CONTRACTS.gameEngine !== ZERO_ADDRESS, refetchInterval: 5000 } });
  const roleR = useReadContract({ address: CONTRACTS.communityController, abi: COMMUNITY_CONTROLLER_ABI, functionName: 'COMMUNITY_MANAGER_ROLE', query: { enabled: CONTRACTS.communityController !== ZERO_ADDRESS } });
  const managerR = useReadContract({ address: CONTRACTS.communityController, abi: COMMUNITY_CONTROLLER_ABI, functionName: 'hasRole', args: roleR.data && address ? [roleR.data, address] : undefined, query: { enabled: !!roleR.data && !!address } });
  const rows: CommunityRow[] = useMemo(() => Array.from({ length: count }, (_, id) => { const r: any = rowsR.data?.[id]; const x: any = r?.status === 'success' ? r.result : undefined; const a = Array.isArray(x) ? x : []; return { id, collection: String(a[0] || zeroAddress), walletRoot: String(a[1] || zeroHash), allocation: Number(a[2] || 0), minted: Number(a[3] || 0), mode: Number(a[4] || 0), active: Boolean(a[5]) } }), [count, rowsR.data]);
  const reserved = Number(reservedR.data || 0n), totalMinted = Number(mintedR.data || 0n), communityMinted = rows.reduce((n, r) => n + r.minted, 0), publicAvailable = Math.max(0, MAX_SUPPLY - totalMinted - reserved), manager = !!managerR.data;
  return <main className="min-h-screen bg-[#0b0d0b] px-4 py-5 md:px-8"><div className="mx-auto max-w-[1500px]">
    <header className="mb-7 flex items-center justify-between border-b border-white/10 pb-4"><div><div className="font-display text-2xl font-bold">GLUTTONS<span className="text-[#ff4b1f]">FUN</span></div><div className="text-[9px] uppercase tracking-widest text-zinc-600">/ communities / separate allocation terminal</div></div><ConnectButton showBalance={false} /></header>
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><Kicker>community allocation stadium</Kicker><h1 className="font-display text-5xl uppercase md:text-7xl">Community Mints</h1><p className="mt-2 max-w-3xl text-xs text-zinc-500">Allocation-critical numbers below are read from CommunityMintController. No demo community rows are rendered.</p></div>{manager && <button onClick={() => setOpen(true)} className="action-btn">+ ADD ONCHAIN COMMUNITY</button>}</div>
    <div className="mt-6 grid gap-3 md:grid-cols-4"><Stat l="RESERVED REMAINING" v={reserved} s="Protected by controller" /><Stat l="COMMUNITY MINTED" v={communityMinted} s="Across configured communities" /><Stat l="PUBLIC AVAILABLE" v={publicAvailable} s="MAX - minted - reserved" /><Stat l="COMMUNITIES" v={count} s="Controller records" /></div>
    <Panel className="mt-4 overflow-hidden"><div className="grid grid-cols-[1.4fr_.8fr_.55fr_.55fr_.55fr] gap-2 border-b border-white/10 p-3 text-[9px] uppercase text-zinc-600"><span>Community / source</span><span>Eligibility</span><span>Allocation</span><span>Minted</span><span>Remaining</span></div>{rows.length ? rows.map(c => <div key={c.id} className="grid grid-cols-[1.4fr_.8fr_.55fr_.55fr_.55fr] items-center gap-2 border-b border-white/5 p-4 text-xs"><div><b>COMMUNITY #{c.id}</b><div className="mt-1 text-[9px] text-zinc-600">{short(c.collection)} · ROOT {c.walletRoot === zeroHash ? '—' : `${c.walletRoot.slice(0, 8)}…`}</div><div className={`mt-1 text-[9px] ${c.active ? 'text-emerald-400' : 'text-zinc-500'}`}>{c.active ? 'ACTIVE' : 'PAUSED'}</div></div><span className="text-zinc-500">{modeName(c.mode)}</span><b>{c.allocation}</b><b>{c.minted}</b><b className="text-[#ff713f]">{Math.max(0, c.allocation - c.minted)}</b></div>) : <div className="p-8 text-center text-[10px] text-zinc-600">NO COMMUNITIES CONFIGURED ON THIS CONTROLLER.</div>}</Panel>
    <div className="mt-4 text-[9px] uppercase text-zinc-600">Display names/logos are presentation metadata, not allocation truth. Keep them in the external metadata store keyed to communityId.</div>
  </div>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-4"><Panel className="w-full max-w-xl p-6"><div className="flex justify-between"><div><Kicker>create controller record</Kicker><h2 className="font-display text-4xl">RESERVE SUPPLY</h2></div><button onClick={() => setOpen(false)}>✕</button></div><div className="mt-5 grid gap-4"><Field l="GUARANTEED ALLOCATION"><input value={form.allocation} onChange={e => setForm({ ...form, allocation: e.target.value.replace(/\D/g, '') })} /></Field><Field l="ELIGIBILITY SOURCE"><select value={form.mode} onChange={e => setForm({ ...form, mode: Number(e.target.value) })}><option value={0}>NFT HOLDERS</option><option value={1}>WALLET LIST / MERKLE ROOT</option><option value={2}>BOTH</option></select></Field>{form.mode !== 1 && <Field l="NFT COLLECTION"><input placeholder="0x…" value={form.collection} onChange={e => setForm({ ...form, collection: e.target.value })} /></Field>}{form.mode !== 0 && <Field l="CURRENT WALLET ROOT"><input placeholder="0x bytes32…" value={form.root} onChange={/*e => setForm({ ...form, root: e.target.value as as `0x${string}` })*/ undefined} /></Field>}</div><div className="mt-6 flex justify-end gap-3"><button className="ghost-btn" onClick={() => setOpen(false)}>CANCEL</button><TxButton label="CREATE + RESERVE" address={CONTRACTS.communityController} abi={COMMUNITY_CONTROLLER_ABI} functionName="createCommunity" args={[form.mode, (form.mode === 1 ? zeroAddress : form.collection), form.mode === 0 ? zeroHash : form.root, Number(form.allocation || 0)]} disabled={!form.allocation || (form.mode !== 1 && !isAddress(form.collection)) || (form.mode !== 0 && !/^0x[a-fA-F0-9]{64}$/.test(form.root))} /></div></Panel></div>}</main>
}
function Stat({ l, v, s }: { l: string; v: string | number; s: string }) { return <Panel className="p-4"><div className="text-[9px] text-zinc-600">{l}</div><div className="mt-2 font-display text-4xl">{v}</div><div className="mt-2 text-[9px] text-zinc-500">{s}</div></Panel> }
function Field({ l, children }: { l: string; children: React.ReactNode }) { return <label><span className="mb-2 block text-[9px] text-zinc-500">{l}</span>{children}</label> }
