'use client';
import { useMemo, useState } from 'react';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useAccount, useReadContract } from 'wagmi';
import { formatEther, isAddress, parseEther, type Address } from 'viem';
import { CONTRACTS, GAME_ENGINE_ABI, NATIVE_SYMBOL, ZERO_ADDRESS } from '@/lib/constants';
import { Panel, Kicker } from '@/components/Terminal';
import { TxButton } from '@/components/TxButton';
import { Header } from '@/components/Header';

type Community = {id:number;name:string;collectionAddress:Address;maxTotalAmountAllowed:number;maxPerWallet:number;allowed:boolean;amountMinted:number};
function norm(raw:any,id:number):Community{const a=Array.isArray(raw)?raw:raw||{};return{id,name:String(a.name??a[0]??`COMMUNITY #${id}`),collectionAddress:String(a.collectionAddress??a[1]??ZERO_ADDRESS) as Address,maxTotalAmountAllowed:Number(a.maxTotalAmountAllowed??a[2]??0),maxPerWallet:Number(a.maxPerWallet??a[3]??0),allowed:Boolean(a.allowed??a[4]??false),amountMinted:Number(a.amountMinted??a[5]??0)}}
const short=(s:string)=>s&&s!==ZERO_ADDRESS?`${s.slice(0,6)}…${s.slice(-4)}`:'—';

export default function Communities(){
  const {address}=useAccount();
  const [open,setOpen]=useState(false);
  const [price,setPrice]=useState('0.004');
  const [armed,setArmed]=useState(false);
  const [form,setForm]=useState({name:'',collection:'',maxTotal:'100',maxPerWallet:'1'});
  const enabled=CONTRACTS.gameEngine!==ZERO_ADDRESS;
  const ownerR=useReadContract({address:CONTRACTS.gameEngine,abi:GAME_ENGINE_ABI,functionName:'owner',query:{enabled}});
  const communitiesR=useReadContract({address:CONTRACTS.gameEngine,abi:GAME_ENGINE_ABI,functionName:'getInvitedNftCommunities',query:{enabled,refetchInterval:5000}});
  const preEndR=useReadContract({address:CONTRACTS.gameEngine,abi:GAME_ENGINE_ABI,functionName:'s_preMintEnd',query:{enabled,refetchInterval:5000}});
  const priceR=useReadContract({address:CONTRACTS.gameEngine,abi:GAME_ENGINE_ABI,functionName:'s_communityMintprice',query:{enabled,refetchInterval:5000}});
  const mintedR=useReadContract({address:CONTRACTS.gameEngine,abi:GAME_ENGINE_ABI,functionName:'s_totalMinted',query:{enabled,refetchInterval:5000}});
  const maxSupplyR=useReadContract({address:CONTRACTS.gameEngine,abi:GAME_ENGINE_ABI,functionName:'MAX_SUPPLY',query:{enabled}});
  const owner=String(ownerR.data||ZERO_ADDRESS); const isOwner=!!address&&owner.toLowerCase()===address.toLowerCase();
  const preMintEnd=Boolean(preEndR.data); const communityPrice=BigInt(priceR.data??0n); const totalMinted=Number(mintedR.data??0n); const maxSupply=Number(maxSupplyR.data??2000n);
  const communities=useMemo(()=>((communitiesR.data||[]) as readonly any[]).map((c,i)=>norm(c,i)),[communitiesR.data]);
  const communityMinted=communities.reduce((n,c)=>n+c.amountMinted,0); const configuredCap=communities.reduce((n,c)=>n+c.maxTotalAmountAllowed,0);
  const refresh=()=>{communitiesR.refetch();preEndR.refetch();priceR.refetch();mintedR.refetch();};

  if(!address||!isOwner)return <><Header isolated/><main className="mx-auto max-w-5xl p-6 md:p-10"><Panel className="p-8 text-center md:p-12"><Kicker>community pre-mint / owner only</Kicker><h1 className="font-display text-5xl uppercase md:text-7xl">ACCESS DENIED</h1><p className="mx-auto mt-5 max-w-2xl text-xs leading-6 text-zinc-500">The latest integration manual moves invited-community configuration into GameEngine and restricts this management surface to the GameEngine Owner. Connect the owner wallet to continue.</p><div className="mt-6 flex justify-center"><ConnectButton showBalance={false}/></div></Panel></main></>;

  return <><Header isolated/><main className="min-h-screen px-4 py-6 md:px-8"><div className="mx-auto max-w-[1500px]">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><Kicker>game engine / owner console</Kicker><h1 className="font-display text-5xl uppercase md:text-7xl">COMMUNITY PRE-MINT</h1><p className="mt-2 max-w-3xl text-xs leading-6 text-zinc-500">Invited NFT collections, dynamic pre-mint price and the irreversible switch to Public Mint now live directly in GameEngine. No separate CommunityMintController is used.</p></div>{!preMintEnd&&<button onClick={()=>setOpen(true)} className="action-btn">+ ADD INVITED COLLECTION</button>}</div>

    <div className="mt-6 grid gap-3 md:grid-cols-5"><Stat l="PHASE" v={preMintEnd?'PUBLIC MINT':'PRE-MINT'} s={preMintEnd?'Community pre-mint permanently ended':'Invited collections only'}/><Stat l="COMMUNITY PRICE" v={`${formatEther(communityPrice)} ${NATIVE_SYMBOL}`} s="Dynamic GameEngine value"/><Stat l="TOTAL MINTED" v={`${totalMinted}/${maxSupply}`} s="All mint routes"/><Stat l="COMMUNITY MINTED" v={communityMinted} s="Configured invited collections"/><Stat l="CONFIGURED CAPS" v={configuredCap} s="Not a reserved-supply guarantee"/></div>

    {!preMintEnd&&<Panel className="mt-4 p-5 md:p-6"><div className="grid gap-5 lg:grid-cols-[1fr_1fr]"><div><Kicker>change community mint price</Kicker><div className="mt-4 flex gap-3"><input value={price} onChange={e=>setPrice(e.target.value)} placeholder="0.004"/><TxButton label="UPDATE PRICE" address={CONTRACTS.gameEngine} abi={GAME_ENGINE_ABI} functionName="changeCommunityMintPrice" args={[parsePrice(price) ?? 0n]} disabled={parsePrice(price)===null} onConfirmed={refresh}/></div><p className="mt-3 text-[9px] uppercase leading-5 tracking-[.08em] text-zinc-600">Price is entered in the active chain native currency. The transaction writes wei to s_communityMintprice.</p></div><div className="pre-mint-danger"><Kicker>irreversible phase switch</Kicker><p>END PRE-MINT permanently opens the standard public mint interface. The supplied contract has no reopen function.</p>{!armed?<button className="ghost-btn mt-4" onClick={()=>setArmed(true)}>ARM END PRE-MINT</button>:<div className="mt-4 flex gap-3"><button className="ghost-btn" onClick={()=>setArmed(false)}>CANCEL</button><TxButton label="CONFIRM: OPEN PUBLIC MINT" address={CONTRACTS.gameEngine} abi={GAME_ENGINE_ABI} functionName="endPreMintedPhase" className="danger-pulse" onConfirmed={()=>{setArmed(false);refresh()}}/></div>}</div></div></Panel>}

    <Panel className="mt-4 overflow-hidden"><div className="grid grid-cols-[1.4fr_.55fr_.55fr_.55fr_.55fr] gap-2 border-b border-white/10 p-3 text-[9px] uppercase text-zinc-600"><span>Invited collection</span><span>Total cap</span><span>Minted</span><span>Wallet cap</span><span>Status</span></div>{communities.length?communities.map(c=><CommunityRow key={c.id} c={c} closed={preMintEnd} refresh={refresh}/>):<div className="p-8 text-center text-[10px] uppercase text-zinc-600">NO INVITED NFT COLLECTIONS REGISTERED.</div>}</Panel>

    <Panel className="mt-4 p-5"><Kicker>architecture boundary</Kicker><div className="grid gap-4 text-[10px] uppercase leading-5 text-zinc-500 md:grid-cols-3"><p><b className="text-white">NO WALLET LISTS IN THIS VERSION.</b><br/>The new GameEngine community flow is collection-based and calls preMint(amount, collectionId).</p><p><b className="text-white">CAPS ONLY INCREASE.</b><br/>The contract's modify functions reject values that are not greater than the current cap.</p><p><b className="text-white">NOT RESERVED-SUPPLY MATH.</b><br/>The supplied GameEngine limits each invited collection but does not expose the prior controller's reservedRemaining invariant.</p></div></Panel>
  </div>

  {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-4"><Panel className="w-full max-w-xl p-6"><div className="flex justify-between"><div><Kicker>game engine / add invite</Kicker><h2 className="font-display text-4xl uppercase">ADD COLLECTION</h2></div><button onClick={()=>setOpen(false)}>✕</button></div><div className="mt-5 grid gap-4"><Field l="COMMUNITY NAME"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="StonkBrokers"/></Field><Field l="NFT COLLECTION ADDRESS"><input value={form.collection} onChange={e=>setForm({...form,collection:e.target.value})} placeholder="0x…"/></Field><Field l="MAX TOTAL MINTS"><input value={form.maxTotal} onChange={e=>setForm({...form,maxTotal:e.target.value.replace(/\D/g,'')})}/></Field><Field l="MAX PER WALLET"><input value={form.maxPerWallet} onChange={e=>setForm({...form,maxPerWallet:e.target.value.replace(/\D/g,'')})}/></Field></div><div className="mt-6 flex justify-end gap-3"><button className="ghost-btn" onClick={()=>setOpen(false)}>CANCEL</button><TxButton label="ADD INVITED COLLECTION" address={CONTRACTS.gameEngine} abi={GAME_ENGINE_ABI} functionName="addInviteCollection" args={[form.name,form.collection,BigInt(form.maxTotal||0),BigInt(form.maxPerWallet||0)]} disabled={!form.name||!isAddress(form.collection)||!Number(form.maxTotal)||!Number(form.maxPerWallet)} onConfirmed={()=>{setOpen(false);refresh()}}/></div><p className="mt-4 text-[9px] uppercase leading-5 text-zinc-600">New collections default to INACTIVE. After creation, use ALLOW MINT on the row when ready.</p></Panel></div>}
  </main></>;
}

function CommunityRow({c,closed,refresh}:{c:Community;closed:boolean;refresh:()=>void}){const [total,setTotal]=useState(String(c.maxTotalAmountAllowed+1));const [wallet,setWallet]=useState(String(c.maxPerWallet+1));const totalValid=Number(total)>c.maxTotalAmountAllowed;const walletValid=Number(wallet)>c.maxPerWallet;return <div className="border-b border-white/5"><div className="grid grid-cols-[1.4fr_.55fr_.55fr_.55fr_.55fr] items-center gap-2 p-4 text-xs"><div><b>#{c.id} · {c.name}</b><div className="mt-1 text-[9px] text-zinc-600">{short(c.collectionAddress)}</div></div><b>{c.maxTotalAmountAllowed}</b><b>{c.amountMinted}</b><b>{c.maxPerWallet}</b><div>{c.allowed?<span className="text-emerald-400">ACTIVE</span>:<span className="text-zinc-500">INACTIVE</span>}</div></div>{!closed&&<div className="community-admin-row"><div>{!c.allowed?<TxButton label="ALLOW MINT" address={CONTRACTS.gameEngine} abi={GAME_ENGINE_ABI} functionName="allowCommunityMint" args={[BigInt(c.id)]} className="secondary-action" onConfirmed={refresh}/>:<span className="admin-lock-label">MINT ALLOWED</span>}</div><div className="community-increase"><span>INCREASE TOTAL CAP</span><input value={total} onChange={e=>setTotal(e.target.value.replace(/\D/g,''))}/><TxButton label="INCREASE" address={CONTRACTS.gameEngine} abi={GAME_ENGINE_ABI} functionName="modifyCollectionMaxAllowed" args={[BigInt(c.id),BigInt(total||0)]} disabled={!totalValid} className="secondary-action" onConfirmed={refresh}/></div><div className="community-increase"><span>INCREASE WALLET CAP</span><input value={wallet} onChange={e=>setWallet(e.target.value.replace(/\D/g,''))}/><TxButton label="INCREASE" address={CONTRACTS.gameEngine} abi={GAME_ENGINE_ABI} functionName="modifyCollectionMaxPerWallet" args={[BigInt(c.id),BigInt(wallet||0)]} disabled={!walletValid} className="secondary-action" onConfirmed={refresh}/></div></div>}</div>}
function Stat({l,v,s}:{l:string;v:string|number;s:string}){return <Panel className="p-4"><div className="text-[9px] text-zinc-600">{l}</div><div className="mt-2 font-display text-3xl md:text-4xl">{v}</div><div className="mt-2 text-[9px] text-zinc-500">{s}</div></Panel>}
function Field({l,children}:{l:string;children:React.ReactNode}){return <label><span className="mb-2 block text-[9px] text-zinc-500">{l}</span>{children}</label>}
function parsePrice(v:string){try{return parseEther(v||'0')}catch{return null}}
