'use client';
import { useRef,useState } from 'react';
import { useAccount,useWriteContract } from 'wagmi';
import { toast } from 'sonner';
import type { Abi,Address } from 'viem';
import { CONTRACTS,ZERO_ADDRESS } from '@/lib/constants';
import { useAtomValue } from 'jotai';
import { protocolAtom } from '@/state/game';

export function humanError(e:any){const s=String(e?.shortMessage||e?.message||e);const map:[string,string][]=[['NotHungry','That action is not available at the current hunger clock.'],['ClockTooLow','This clock is too low for that action.'],['Protected','Target is Poison Protected. Wait for the shield timer to expire.'],['SelfPoison','You cannot poison the same Glutton.'],['MintClosed','Mint is closed. Game Start cannot be extended.'],['MaxSupplyExceeded','All Gluttons have entered.'],['NotOwner','Your connected wallet does not own the required Glutton.'],['InvalidValue','Wrong transaction value. Refresh and retry.'],['InvalidMintValue','Wrong mint value. Refresh and retry.'],['InvalidState','That action is not legal in the current token or game state.'],['AlreadyStarted','The game has already started.'],['AlreadySettled','The table is already settled.'],['NotLastSupper','This action only exists at the final table.'],['NotUnanimous','The Truce is not unanimous.'],['NormalMintNotAllowed','Public Mint is not open yet. This is still Community Pre-Mint.'],['PreMintPhaseEnded','Community Pre-Mint has ended. Use Public Mint.'],['MaxSupplyForInviteExceeded','That invited community has reached its mint allowance.'],['CommunityMintNotAllowed','That invited community is not active for minting.'],['NotCommunityHolder','This wallet does not hold an NFT from the selected invited community.'],['InvalidMaxPerWalletAmount','This mint would exceed the wallet limit.'],['AlreadyAllowed','That invited community is already active.']];return map.find(([k])=>s.includes(k))?.[1]||s||'Transaction failed or was rejected. No confirmed state changed.';}
function contractAlias(address:Address){if(address.toLowerCase()===CONTRACTS.gameEngine.toLowerCase())return'gameEngine';if(address.toLowerCase()===CONTRACTS.prizeVault.toLowerCase())return'prizeVault';return null;}
function serialize(v:any):any{if(typeof v==='bigint')return{__gluttonsBigInt:v.toString()};if(Array.isArray(v))return v.map(serialize);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,serialize(x)]));return v;}
async function serverPreflight(account:Address,address:Address,functionName:string,args:readonly unknown[],value?:bigint){const contract=contractAlias(address);if(!contract)return true;const r=await fetch('/api/read/simulate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contract,functionName,args:serialize(args),value:value?.toString(),account}),cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.ok&&j.ok)return true;if((r.status===429||r.status>=500)&&j.retryable!==false)return false;throw new Error(j.error||'Preflight failed.');}
function touchedTokenIds(functionName:string,args:readonly unknown[]){const one=new Set(['feed','enterFast','powerFridge','voteTruce']);const two=new Set(['poison','liveDevour','consumeCorpse']);try{if(one.has(functionName))return[Number(args[0])].filter(Number.isSafeInteger);if(two.has(functionName))return[Number(args[0]),Number(args[1])].filter(Number.isSafeInteger);if(functionName==='reap'||functionName==='settleGame')return(Array.isArray(args[0])?args[0]:[]).map(Number).filter(Number.isSafeInteger).slice(0,16);return[]}catch{return[]}}
async function notifyIndexer(functionName:string,args:readonly unknown[],notBeforeBlock=0){const tokenIds=touchedTokenIds(functionName,args);if(!tokenIds.length)return;try{await fetch('/api/read/touch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tokenIds,notBeforeBlock}),cache:'no-store'})}catch{}}
async function waitReceipt(hash:`0x${string}`){const waits=[1_800,3_000,5_000,8_000,12_000,18_000,25_000,30_000,30_000,30_000];for(const ms of waits){await new Promise(r=>setTimeout(r,ms));try{const r=await fetch(`/api/read/tx/${hash}`,{cache:'no-store'});if(r.status===202||r.status===429||r.status>=500)continue;if(!r.ok)continue;const j=await r.json();if(j.found)return j;}catch{}}return null;}

export function TxButton({label,address,abi,functionName,args=[],value,disabled=false,className='',onConfirmed,preflight=false,successLabel='CONFIRMED ✓',successMs=2200}:{label:string;address:Address;abi:Abi|readonly unknown[];functionName:string;args?:readonly unknown[];value?:bigint;disabled?:boolean;className?:string;onConfirmed?:()=>void;preflight?:boolean;successLabel?:string;successMs?:number}){
 const{address:account}=useAccount();const p=useAtomValue(protocolAtom);const w=useWriteContract();const fired=useRef<string|undefined>(undefined);const[tracking,setTracking]=useState(false);const[pendingHash,setPendingHash]=useState<`0x${string}`|null>(null);const[trackingDelayed,setTrackingDelayed]=useState(false);const[justConfirmed,setJustConfirmed]=useState(false);
 const corePreflight=address.toLowerCase()===CONTRACTS.gameEngine.toLowerCase()||address.toLowerCase()===CONTRACTS.prizeVault.toLowerCase();
 const click=async()=>{let submitted=false;try{if(preflight||corePreflight){if(!account){toast.error('Connect the wallet and retry.');return;}const verified=await serverPreflight(account,address,functionName,args,value);if(!verified)toast.message('Preflight service is busy. Your wallet and the contract will perform the final validation.');}setTracking(true);setTrackingDelayed(false);const hash=await w.writeContractAsync({address,abi:abi as Abi,functionName,args,value}as any);submitted=true;setPendingHash(hash);toast.message('Transaction submitted. Waiting for onchain confirmation.');const receipt=await waitReceipt(hash);if(!receipt){setTrackingDelayed(true);toast.warning('Transaction is submitted, but confirmation tracking is delayed. Check the explorer before attempting anything again.');return;}if(receipt.status!=='success')throw new Error('Transaction reverted onchain.');if(fired.current!==hash){fired.current=hash;setPendingHash(null);if(address.toLowerCase()===CONTRACTS.gameEngine.toLowerCase())void notifyIndexer(functionName,args,Number(receipt.blockNumber||0));setTrackingDelayed(false);setJustConfirmed(true);toast.success('Confirmed onchain.');onConfirmed?.();setTimeout(()=>setJustConfirmed(false),successMs);}}catch(e){if(submitted)setPendingHash(null);toast.error(humanError(e));}finally{setTracking(false)}};
 const requiresFreshCanonicalRead=corePreflight;const staleBlock=requiresFreshCanonicalRead&&p.rpcDegraded;const off=disabled||staleBlock||address===ZERO_ADDRESS||w.isPending||tracking||Boolean(pendingHash);const text=staleBlock?'STATE SYNCING — ACTION PAUSED':w.isPending?'OPEN WALLET…':tracking?'CONFIRMING ONCHAIN…':trackingDelayed&&pendingHash?'TX SUBMITTED — CHECK EXPLORER':pendingHash?'TX SUBMITTED — VERIFYING…':justConfirmed?successLabel:label;return<button data-fx-sound onClick={click} disabled={off} title={pendingHash||undefined} className={`action-btn ${className}`}>{text}</button>;
}
